site_name: GCES - KDE Frameworks
theme: yeti

nav:
  - Home: index.md
  - Como Contribuir: como-contribuir.md
  - Sprints:
    - Sprint 0: sprints/sprint0.md
    - Sprint 1: sprints/sprint1.md
  - Contribuições Individuais:
    - Daniel Fernandes Silva: diario/daniel-fernandes-silva/diario.md
    - Felipe de Aquino Campelo: diario/felipe-de-aquino-campelo/diario.md
    - Gabryel Nicolas Soares de Sousa: diario/gabryel-nicolas-soares-de-sousa/diario.md
    - Kauan Jose de Lima Barbosa Campos: diario/kauan-jose-de-lima-barbosa-campos/diario.md
    - Lucas Martins Gabriel: diario/lucas-martins-gabriel/diario.md
    - Renann de Oliveira Gomes: diario/renann-de-oliveira-gomes/diario.md
    - Caio Alexandre Ornelas Silva: diario/caio-alexandre-ornelas-silva/diario.md